name: Code CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  windows:
    runs-on: windows-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2

      - name: Setup 1.17 Golang version
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Verify dependencies
        run: go mod verify

      - name: Build executable
        run: go build -ldflags "-w -s" main.go